/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.school;

/**
 *
 * @author nagashreeseshadri
 */
public class SchoolWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SchoolJPanel
     */
    public SchoolWorkAreaJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStudentInfoHeading1 = new javax.swing.JLabel();
        btnManageClassrooms = new javax.swing.JButton();
        btnManageClassrooms1 = new javax.swing.JButton();
        lblStudentInfoHeading2 = new javax.swing.JLabel();

        lblStudentInfoHeading1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblStudentInfoHeading1.setText("Welcome to the Day Care");

        btnManageClassrooms.setText("List Classrooms");

        btnManageClassrooms1.setText("Enter as Admin");
        btnManageClassrooms1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageClassrooms1ActionPerformed(evt);
            }
        });

        lblStudentInfoHeading2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblStudentInfoHeading2.setText("What do you want to do?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(lblStudentInfoHeading1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblStudentInfoHeading2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnManageClassrooms1)
                            .addComponent(btnManageClassrooms))))
                .addContainerGap(227, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnManageClassrooms, btnManageClassrooms1});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblStudentInfoHeading1)
                .addGap(32, 32, 32)
                .addComponent(lblStudentInfoHeading2)
                .addGap(68, 68, 68)
                .addComponent(btnManageClassrooms1)
                .addGap(18, 18, 18)
                .addComponent(btnManageClassrooms)
                .addContainerGap(189, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageClassrooms1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageClassrooms1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageClassrooms1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageClassrooms;
    private javax.swing.JButton btnManageClassrooms1;
    private javax.swing.JLabel lblStudentInfoHeading1;
    private javax.swing.JLabel lblStudentInfoHeading2;
    // End of variables declaration//GEN-END:variables
}
