/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.groups;

/**
 *
 * @author nagashreeseshadri
 */
public class GroupJPanel extends javax.swing.JPanel {

    /**
     * Creates new form GroupJPanel
     */
    public GroupJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStudentInfoHeading1 = new javax.swing.JLabel();
        lblGroupID = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblGroupInfoStudent = new javax.swing.JTable();
        lblFirstName1 = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblEmployeeID = new javax.swing.JLabel();
        lblTeacherInfoHeading = new javax.swing.JLabel();
        lblTeacherID = new javax.swing.JLabel();
        lblFNameTeacher = new javax.swing.JLabel();
        lblLastNameTeacher = new javax.swing.JLabel();
        btnStudentInfo = new javax.swing.JButton();

        lblStudentInfoHeading1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblStudentInfoHeading1.setText("Hello, you are viewing the Group");

        lblGroupID.setText("jLabel1");

        tblGroupInfoStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Student ID", "Student First Name", "Student Last Name"
            }
        ));
        jScrollPane2.setViewportView(tblGroupInfoStudent);

        lblFirstName1.setText("Last Name:");

        lblFirstName.setText("First Name:");

        lblEmployeeID.setText("Employee ID:");

        lblTeacherInfoHeading.setText("Teacher Information for this group");

        lblTeacherID.setText("jLabel1");

        lblFNameTeacher.setText("jLabel1");

        lblLastNameTeacher.setText("jLabel1");

        btnStudentInfo.setText("View Student Info");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(lblStudentInfoHeading1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(lblGroupID, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTeacherInfoHeading)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblFirstName)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblFNameTeacher)
                                        .addGap(189, 189, 189))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblEmployeeID)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblTeacherID)
                                        .addGap(177, 177, 177)))
                                .addComponent(lblFirstName1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblLastNameTeacher)))))
                .addContainerGap(143, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnStudentInfo)
                .addGap(185, 185, 185))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStudentInfoHeading1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGroupID)
                .addGap(44, 44, 44)
                .addComponent(lblTeacherInfoHeading)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployeeID)
                    .addComponent(lblTeacherID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(lblFirstName1)
                    .addComponent(lblFNameTeacher)
                    .addComponent(lblLastNameTeacher))
                .addGap(63, 63, 63)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnStudentInfo)
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStudentInfo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblEmployeeID;
    private javax.swing.JLabel lblFNameTeacher;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblFirstName1;
    private javax.swing.JLabel lblGroupID;
    private javax.swing.JLabel lblLastNameTeacher;
    private javax.swing.JLabel lblStudentInfoHeading1;
    private javax.swing.JLabel lblTeacherID;
    private javax.swing.JLabel lblTeacherInfoHeading;
    private javax.swing.JTable tblGroupInfoStudent;
    // End of variables declaration//GEN-END:variables
}
